version: '20.10.8'
service:
  db:
   command: mysqld --default-authentication-plugin=mysql_native_password
   restart: always
   build:
    context: . 
    dockerfile: Dockerfile
   environment:
    TZ: America/Sao_Paulo
    MYSQL_ROOT_PASSWORD: 
    MYSQL_USER: root 
    MYSQL_PASSWORD: 159753/
    MYSQL_DATABASE: bd_blogpessoal
   ports:
    - "3308:3306"
   network:
    - generation-network
  blogpessoal-api:
    restart: always
    build: ./blogpessoal-api
    working_dir: ./blogpessoal-api
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./blogpessoal-api:/blogpessoal-api
      - ~/.m2:/root/.m2
    ports:
      - "9000:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    network:
     - generation-network
networks:
   generation-network:
     driver: bridge 